### ISSUE TITLE
building.md#build-packages arm64 and amd64 build args is wrong?

### ISSUE THREAD

**Issue by mxxmusic** [microsoft/CBL-Mariner#294]
# Still from the toolkit folder, copy the toolchain archive built in the previous step into the toolkit folder
mv ../build/toolchain/toolchain_built_rpms_all.tar.gz .

# Build ALL packages FOR AMD64  this is for ARM64?
sudo make build-packages -j$(nproc) CONFIG_FILE= TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz DOWNLOAD_SRPMS=y REBUILD_TOOLS=y REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=y PACKAGE_IGNORE_LIST="openjdk8 openjdk8_aarch64 shim-unsigned-aarch64"

# Build ALL packages FOR ARM64 this is for AMD64  ?
sudo make build-packages -j$(nproc) CONFIG_FILE= TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz DOWNLOAD_SRPMS=y REBUILD_TOOLS=y REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=y PACKAGE_IGNORE_LIST="openjdk8 openjdk8_amd64 shim-unsigned-amd64"

**Comment by dmcilvaney** [comment]
Thanks for pointing this out, its not particularly intuitive and we probably should have explained!

If you are referring to the `PACKAGE_IGNORE_LIST=` variable, they are intentionally reversed. These are an artifact from an old bug build system and the slightly odd setup of those packages (I believe since resolved). The intent was to stop some of the tools attempting to process packages they were incapable of parsing due to an architecture mismatch.

I'm almost certain you can omit those completely now, and I'll make a note to clean this up for the next version (we are reworking some of the tooling anyways).

**Comment by dmcilvaney** [comment]
Ah, realized the issue. Some of the documentation fixes haven't bubbled up to the main branch yet.
I would recommend using https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/README.md which has some streamlined build instructions.

**Comment by jslobodzian** [comment]
Closing this issue as resolved.  Please open a new one if the current documentation has not fully addressed your concern.
