### ISSUE TITLE
Error when trying to make an image a CBL-Mariner 2.0 from CBL-Mariner 2.0

### ISSUE THREAD

**Issue by ohault** [microsoft/CBL-Mariner#3196]
On, https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/building/prerequisites-mariner.md, dnf or tdnf and this page should be updated for 2.0

Following https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/quick_start/quickstart.md#build-and-boot-an-image, I got these errors
![image](https://user-images.githubusercontent.com/5320161/174451148-7a1bd7fc-6017-464d-920b-8ba227a5fbfa.png)

**Comment by oliviacrain** [comment]
Thanks for the report, and apologies for the slow response time. This error is occurring because our SRPM packer tool can't find package sources, which are stored in a separate blobstore to avoid bloating this git repo.

Workaround: Pass `SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core` when invoking `make`, so our tool knows where to 

Full fix: I've opened up #3391 to set a default `SOURCE_URL`, so that you won't need to pass it in the future.

**Comment by mfrw** [comment]
Fixed as per PR:
- #3391
