### ISSUE TITLE
Provide GitHub Actions or ADO recipes for anyone to create Mariner binaries

### ISSUE THREAD

**Issue by mjsabby** [microsoft/CBL-Mariner#322]
It would be great if we could create a yaml file that then anyone could use to setup their own GitHub action or Azure DevOps pipeline to build Mariner.

Then we can have a continuous integration build of Mariner that any one can build.

**Comment by sr229** [comment]
I think we can follow the build instructions then come up with a GitHub Actions file for it. I would love to run my own deriverative of CBL-Mariner soon.

**Comment by dmcilvaney** [comment]
Thanks for the interest!
tl,dr: We have a stable nightly actions file here we aren't using yet you can have a peek at: https://github.com/microsoft/CBL-Mariner/blob/1.0/.github/workflows/quickstart.yml

If you are using the term 'derivative' to refer to a repo with just a hand full of custom specs (see end) this will also work fine. For the more general case of doing scheduled builds for the base repo:

### Base Repo Pipelines:
There are a few issues we have been struggling with internally in regards to pipelines. The issue stems from how to get the source files to build the packages with.

There are two quickstart builds paths, using prebuild binary packges (rpms), or pre-packages source rpms (srpms). These both are taken from our public package server.

The issue with CI and other nightly builds is:
- We only publish rpms and srpms to the public server when we believe they are stable/tested.
- A nightly build, or CI build, will often have bumped a package version (ie the source file will go from `foo-1.2.3.tar.gz` -> `foo-1.2.4.tar.gz`).
- The published package server will not have `foo-1.2.4.src.rpm` available for the SRPM based build to extract sources from, nor with the final rpm be available.
- Build will fail with an unresolved dependency for foo-1.2.4 (since the build can see the spec file locally, and knows it should be *somewhere*)

Internally we maintain a source server which is able to serve these *.tar.gz files (we build with `DOWNLOAD_SRPMS=n`) to the build (See documentation on `SOURCE_URL=`). This means that so long as we upload any source archive we want to try building to this internal server before the build we can do internal test builds.

It is certainly possible to run the quickstart builds nightly on a stable tag though (https://github.com/microsoft/CBL-Mariner/blob/1.0/.github/workflows/quickstart.yml). That hasn't made its way to the main branch yet, but it does work. We are also considering expanding that workflow to actually validate the exact commands in the quickstart guide.

### Derivative Repo Pipelines:
As for derivative builds (ie /SPECS has **only** your custom spec files and no base packages), its much easier. It is quite reasonable to directly check in all the source files (see https://github.com/microsoft/CBL-Mariner/issues/184#issuecomment-708716561). If the sources are checked in to the repo you can 100% run builds on any given commit.

**Comment by sr229** [comment]
Don't you guys have a testing or nightly pipeline? That seems rather too basic vs how projects like Fedora does it where they have pipelines for Rawhide and Stable

**Comment by dmcilvaney** [comment]
Sorry for the confusion. Yes, we have a full set of pipelines for our internal use cases. There are some challenges creating analogues in Github (takes too long to run, access to sources, etc.). I'll see about getting the 1.0-stable workflow bumped into the main branch.

**Comment by dmcilvaney** [comment]
Added a badge that displays the status of the quick start validation workflow here: https://github.com/microsoft/CBL-Mariner/pull/377

I'll make sure to bring up internally providing some sample ADO yaml files as well, but we don't have anything to share right now.

**Comment by mjsabby** [comment]
Anything to share now? It would be really cool if this repo becomes the easiest way to get a distribution (sure of the CentOS kind) with the parameters you'd like.

**Comment by jslobodzian** [comment]
At this time our yaml files are maintained internally. There are public build instructions provided in the CBL-Mariner and CBL-MarinerDemo repositories that can be leveraged to build your own build pipelines if desired.
