### ISSUE TITLE
Docker images are outdated

### ISSUE THREAD

**Issue by floriankoch** [microsoft/CBL-Mariner#4290]
the mariner docker images are outdated, latest update is 2.0.20221110 , latest mariner release is 2.0.2022111**9**

NAME="Common Base Linux Mariner"
VERSION="2.0.20221110"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

**Comment by oliviacrain** [comment]
Thanks for the note! It looks like there's a misunderstanding here- there's no `2.0.20221119` release. Perhaps you meant [`1.0.20221119`](https://github.com/microsoft/CBL-Mariner/releases/tag/1.0.20221119-1.0)?

Going to close this issue, since there's not really any action we can take here (`1.0.20221119` containers are published). Feel free to re-open if I'm mistaken!

**Comment by floriankoch** [comment]
@oliviacrain the Version number is from the os-release file inside the Container, so it should be correct, or do i miss something?

**Comment by oliviacrain** [comment]
The `os-release` file looks fine there. I think you're mixing up `1.0` and `2.0` releases, since we don't actually have a `2.0.20221119` release.

**Comment by floriankoch** [comment]
@oliviacrain you are right, thanks
