### ISSUE TITLE
core:1.0 Docker image now includes v8 variant in arm64 manifest

### ISSUE THREAD

**Issue by dagood** [microsoft/CBL-Mariner#4856]
I noticed today that the `cblmariner.azurecr.io/base/core:1.0` manifest now includes `"variant": "v8"`. This broke my build because my infrastructure checks that the images we get match what we expect, and until now, Mariner images haven't had `"variant"` filled in.

This is how I checked. It seems that this has changed for Mariner 1.0 but not 2.0:

```
#> docker manifest inspect cblmariner.azurecr.io/base/core:1.0
...
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "os.version": "cbl-mariner-1.0",
            "variant": "v8"
         }
...
#> docker manifest inspect cblmariner.azurecr.io/base/core:2.0
...
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "os.version": "cbl-mariner-2.0"
         }
...
```

* Why was this changed?
* Will this be changed in the 2.0 images as well? When?

**Comment by dagood** [comment]
> * Will this be changed in the 2.0 images as well? When?

It looks like the answers are "yes", and "now". 😄 This has changed between when I filed the issue and another manifest check just now:

```
#> docker manifest inspect cblmariner.azurecr.io/base/core:2.0
...
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "os.version": "cbl-mariner-2.0",
            "variant": "v8"
         }
...
```

I still need to know if this is intentional, or if "variant" may disappear again in the future.

**Comment by christopherco** [comment]
@dagood Thanks for reporting this. Checking internally to see if this was an intentional change. Will report back shortly.

**Comment by mthalman** [comment]
FWIW, I did log an internal issue about the fact that variant was missing from the metadata: https://microsoft.visualstudio.com/OS/_workitems/edit/38266794 (internal Microsoft link). That's still open and doesn't look to have been touched at all. But it seems like it's finally been fixed.

**Comment by mandeepsplaha** [comment]
Thank you for reporting this @dagood. The addition of variant wasn't intentional and we found that it is linked to the auto-upgrade of the 1ES build images that we use in our pipeline's agent pools. As part of the image upgrade, the docker version was upgraded which resulted in the variant being automatically added for the ARM64 images for both Mariner 1.0 and 2.0. However, this issue also brought to our attention the internal issue that @mthalman had logged and it seems like having variant resolves that issue.

To answer you question about whether this change will disappear in the future - no. We plan to explicitly set variant for our ARM64 manifests so that creating it is not dependent on a particular docker version.

Additionally, we recommend that you use MCR for pulling Mariner images. The MAR portal now has cbl-mariner images: https://mcr.microsoft.com/en-us/product/cbl-mariner/base/core/about.

Please let me know if we can close this issue now.

**Comment by dagood** [comment]
Great! Thanks for looking into it. Closing the issue.
