### ISSUE TITLE
`curl` executable missing from 2.0.20230621 base container

### ISSUE THREAD

**Issue by guy-microsoft** [microsoft/CBL-Mariner#5759]
Version 2.0.20230621 introduced a breaking change when working with curl.

`docker run mcr.microsoft.com/cbl-mariner/base/core:2.0.20230621 curl https://google.com -X -GET`
results with the following error:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown.`

While:
`docker run mcr.microsoft.com/cbl-mariner/base/core:2.0.20230609 curl https://google.com -X -GET
`
works as expected.

**Comment by oliviacrain** [comment]
Thanks for the report!

Closing the loop on this: this issue was also raised internally on 28 Jun. That same day, we made an internal hotfix to our container publishing tooling and re-published the affected containers so that they included `curl`.

A more permanent fix was added in #5762 to include `curl` and `grep` as dependencies of our `core-packages-container` package, ensuring that this does not happen again in the future.
