### ISSUE TITLE
Using build instructions for toolchain to download packages errors with 404 Not Found

### ISSUE THREAD

**Issue by cwyborny** [microsoft/CBL-Mariner#6015]
Package manifests for aarch64, probably same for x86 are looking for version not found at packages.microsoft.com.  

- curl-8.2.1-1.cm2.aarch64.rpm is not available, but curl-8.0.1-2.cm2.aarch64.rpm is.  
- curl-devel-8.2.1-1.cm2.aarch64.rpm is not available but curl-devel-8.0.1-2.cm2.aarch64.rpm is.
- curl-libs-8.2.1-1.cm2.aarch64.rpm is not available but curl-libs-8.0.1-2.aarch64.rpm is
- curl-debuginfo-8.2.1-1.cm2.aarch64.rpm is not available but curl-debuginfo-8.0.1-2.aarch64.rpm is
- kernel-headers-5.15.125.1-2.cm2.aarch64.rpm is not available but kernel-headers-5.15.122.1-2.aarch64.rpm is.

Locally modifying these entries in the manifest files allows build to continue.

**Comment by mfrw** [comment]
I think you might be trying to build `main` or `2.0`; if that is the case, this is an expected behaviour.
Since `main` / `2.0` is our transient branch, all packages that are listed in the manifest might not have been released yet & thus they would not be availible in the package repo yet.

If on the other hand this happened with `2.0-stable` tag (unlikely), then it would be unexpected.

**Comment by cwyborny** [comment]
Sorry, should have made that clear.  I thought I was building on 2.0-stable, but will double check it.  May have pulled the tip of the branch unintentionally.

**Comment by cwyborny** [comment]
Yes, I had unintentially pulled the branch instead of the tag when trying to make sure I was updating.
