### ISSUE TITLE
Mariner 2.0 stable toolkit now needs golang-1.20 in Ubuntu 18

### ISSUE THREAD

**Issue by Pravila00** [microsoft/CBL-Mariner#6397]
After the latest release of Mariner2.0-stable, today my build of the Mariner 2.0 toolkit using Ubuntu stopped working properly. It seems that now some packages from the toolkit are using golang-1.20 features.

For example, [imagecustomizerlib](https://github.com/microsoft/CBL-Mariner/tree/ae993d0b3288b1bb291f5f468169fa36b681b4d4/toolkit/tools/pkg/imagecustomizerlib) now uses filepath.IsLocal which is only added [after golang-1.20](https://pkg.go.dev/path/filepath#IsLocal). These are the logs when building the toolkit:

```
# github.com/microsoft/CBL-Mariner/toolkit/tools/pkg/imagecustomizerlib
pkg/imagecustomizerlib/imagecustomizer.go:149:15: undefined: filepath.IsLocal
pkg/imagecustomizerlib/imagecustomizer.go:328:34: undefined: strings.CutPrefix
```

I believe the requirements for Ubuntu18 should be updated at [prerrequisites-ubuntu.md](https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/building/prerequisites-ubuntu.md), as now golang-1.20 is needed.

**Comment by christopherco** [comment]
Thanks for highlighting this @Pravila00 and sorry about the disruption. We had the doc changes prepared (https://github.com/microsoft/CBL-Mariner/commit/aafec9588216f49331fc9e30b9c1ad0dc070056f) but looks like they had missed the 2.0-stable release train.

Tagging @PawelWMS, @cwize1 , @eric-desrochers for awareness

In general, we recommend updating to a Ubuntu 22.04 or Mariner 2.0 environment since Ubuntu 18.04 is EOL. Additionally, golang 1.19 recently went EOL as well, so it is recommended to move forward to golang 1.20
