### ISSUE TITLE
kata-containers: upgrade version  `3.1.0 -> 3.2.0`

### ISSUE THREAD

**Issue by mfrw** [microsoft/CBL-Mariner#6656]
Upgrade the vanila `kata-containers` packages from version `3.1.0` -> `3.2.0` and modify any internal patches that were targeted for `3.1.0` to apply cleanly on `3.2.0`.

Workitem: https://microsoft.visualstudio.com/OS/_workitems/edit/45063880
```[tasklist]
### Tasks
```

**Comment by sprt** [comment]
FYI this is currently blocked as 3.2.0 now depends on the Rust version of virtiofsd (rather than C) and that is a breaking change.

Plan for Mariner 2.0 is to split virtiofsd into two different such packages (to not break any potential current C virtiofsd users) and point our Kata 3.2.0 package to the Rust virtiofsd.

For Mariner 3.0, we will evaluate if we can get rid of the C virtiofsd altogether.
